### ISSUE TITLE
que hacemos con las imagenes muy chicas?

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#101]
Si subimos una imagen de 10x10, la va a estirar hasta el tamaño que necesite mostrarla. O sea 50, 150, etc dependiendo en que view está.
Quizás para los thumbs esto esté bien y para los resize no. no se. (diferencia entre thumbs y resize lo nombré en #99  )
Si subimos una imagen muy chica a Facebook en la galeria el thumb se ve estirado, pero a la hora de ver esa imagen en el theater la muestra en el tamaño original. Podríamos seguir este comportamiento.
discuss

**Comment by aguspuentes** [comment]
Yo dejaría que los thumbs se estiren ya que eso es sólo para la tabla donde se muestran todos los asistidos o interacciones, pero para la galería de fotos me parece que no corresponde estirar la imagen por ejemplo a 720 x 720, en ese caso la dejaría en su tamaño original si la imagen es más chica que la resolución que definimos.

**Comment by CrimsonGlory** [comment]
estoy de acuerdo. 
En las listas, el thumb se estira.
en la galeria de imagenes, cuando haces click en la imagen, que no se estire.
y en los avatares del person.show?

**Comment by aguspuentes** [comment]
Mmm en los avatares del show person creo que haría similar a lo de la galería de imágenes. Si la foto  es más grande del tamaño que definimos la re dimensionaría, pero si es más chica la dejaría en su tamaño original porque en el show de person la foto se muestra más grande que en los thumbs y se va a ver muy feo si la estiramos y la foto era de 10 x 10 por ejemplo.

**Comment by CrimsonGlory** [comment]
Me acabo de fijar y con el código actual jamás la estira.
hay que mover bastante código si queremos hacer que en los thumbs la estire. creo que no vale la pena por el momento.

**Comment by aguspuentes** [comment]
Ok. Por lo que yo anduve probando en general todas las imágenes que subí se veían bastante bien, incluso varias que no eran cuadradas sacadas con el celu. Así que no estaría mal que quede así.

**Comment by CrimsonGlory** [comment]
queda asi entonces.
