### ISSUE TITLE
¿quienes deberían poder cambiar el avatar de un asistido?

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#104]
¿quienes deberían poder cambiar el avatar de un asistido?
Los admins, el creador del asistido?, alguien más?

**Comment by aguspuentes** [comment]
Me parece que utilizaría el mismo criterio que se usa para mostrar el botón "+ Agregar archivos". Si el usuario puede cambiarle la foto al asistido también debería poder cambiarle el avatar. Me parece que hoy en día cualquier usuario que no sea new-user puede cambiarle la foto al asistido, así que yo usaría ese mismo criterio para el avatar.

**Comment by CrimsonGlory** [comment]
Tiene sentido. Lo crearía como un permiso más, el cual todos los roles que tienen el permiso de agregar fotos, también tienen este permiso.

**Comment by aguspuentes** [comment]
Claro. Se puede agregar un permiso "add-files-to-people" y se lo agregaríamos a todos los roles salvo al rol new-user. Los new users sólo podrían agregar archivos a los asistidos que crearon ellos.
