### ISSUE TITLE
en el buscador aparecen solo 10 resultados

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#130]
Debería haber paginación.

**Comment by aguspuentes** [comment]
Por la forma en la que se hace la paginación al pasar a la siguiente hoja se perderían los parámetros de búsqueda. Tal vez para el buscador lo mejor sería subir la cantidad de resultados a 20 o 30 y si la búsqueda supera esa cantidad de resultados mostrarle un mensaje al usuario que le indique que su parámetro de búsqueda es demasiado amplio (varios buscadores hacen esto). De esta forma también controlaríamos el caso hipotético de un "new-user" que quisiera sacar información de todos los asistidos buscando por ejemplo "a".

**Comment by aguspuentes** [comment]
Sino habría que buscar una forma distinta de paginar en las búsquedas, acá hay un video de laracast que explica una forma de paginar:
https://laracasts.com/lessons/crazy-simple-pagination

**Comment by CrimsonGlory** [comment]
mientras tanto cambialo a 30 y que quede el issue acá para el futuro.

**Comment by aguspuentes** [comment]
Se decidió limitar los resultados del buscador a 30 y mostrar un mensaje en caso de que se supere el límite.
En la issue #134 se discute si conviene paginar el buscador o dejarlo así.
