### ISSUE TITLE
en peron.create si pones una fecha invalida sale error

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#31]
en /person/{id}/interaction/create si pones una fecha invalida sale error de laravel.

```
InvalidArgumentException in Carbon.php line 393: Trailing data

    in Carbon.php line 393
    at Carbon::createFromFormat('Y-m-d', '2015-05-0723423') in Interaction.php line 32
```

Debería volver a la misma view, con el campo descripción completado como estaba antes, el campo fecha en la fecha de hoy, y que aparezca en rojo el error de fecha inválida.
uno de los laracasts explica como hacer esto.

**Comment by aguspuentes** [comment]
Solucionado. Faltaba la validación del campo "date" de la interacción en el método rules() del CreateInteractionRequest.
