### ISSUE TITLE
en la view person.photos el menu se pone en negrita

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#34]
en la galeria de fotos (person/{id}/photos ) el menu se pone en negrita.  Probablemente el .css que hay que incluir en el header este haciendo lio.

**Comment by aguspuentes** [comment]
Solucionado. La línea del link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" era la que ponía en negrita el menú. La galería funciona exactamente igual sin ese link.
