### ISSUE TITLE
cuando se avisa a alguien por mail de una nueva interaccion y falla el smtp

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#36]
cuando se avisa a alguien por mail de una nueva interaccion y falla el smtp (o hay otro error), se debería redirigir al person@show y avisar que no se pudo enviar el email. (ahora sale error)

**Comment by aguspuentes** [comment]
Solucionado. Se agrega un try/catch de la excepción para el método Mail::send().
En caso de que se produzca algún error al enviar un mail, se redirige a person@show con un parámetro adicional mostrando el mensaje de error.
