### ISSUE TITLE
validar que sea un mail valido.

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#38]
A la hora de derivar hay que validar que sea un mail válido.
Swift_RfcComplianceException in MailboxHeader.php line 348: Address in mailbox given [ff676776f] does not comply with RFC 2822, 3.6.2.

**Comment by aguspuentes** [comment]
Se corrige el error desde el controller capturando una excepción genérica en el try/catch para prevenir cualquier otro tipo de excepción que pueda generarse al enviar un mail.
Queda pendiente validar desde el formulario para que verifique que lo que se ingresó en el campo tenga formato de correo electrónico.
