### ISSUE TITLE
setBirthdateAttribute() no esta siendo usada.

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#4]
La función está pero no se está autocompletando la hora y minutos de birthdate.
ya no me acuerdo en que lesson del laracast nombraba esto.

**Comment by CrimsonGlory** [comment]
El update de Person en master no funicona cuando no pones la fecha de nacimiento. No se a partir de qué comit empezó a pasar esto. Pero explota en la función setBirthdateAttribute(). La comenté. Hay que llamarla solo cuando ingresas una date válida.

**Comment by aguspuentes** [comment]
Se corrigió el problema al editar una persona que no tenía fecha de nacimiento. Sólo había que preguntar si $date era distinto de null antes de setear el atributo birthdate. Además se agregó en las validaciones que birthdate debe ser un date.
