### ISSUE TITLE
Roles y Permisos para users.

### ISSUE THREAD

**Issue by aguspuentes** [CrimsonGlory/posaderos#42]
Se deben agregar los roles:
- Nuevo usuario.
- Explorador.
- Posadero.
- Administrador.

En principio, un rol más avanzado contendrá los mismos permisos que los roles inferiores a él más otros permisos adicionales.

**Comment by aguspuentes** [comment]
Acá dejo un link a Github que explica como instalar un package que permite manejar los roles y permisos de usuarios:

https://github.com/Zizaco/entrust

**Comment by CrimsonGlory** [comment]
Aca hay otro, pero a simple vista entrust parece más completo.
https://github.com/romanbican/roles
edit: Me gusta más entrust.

**Comment by aguspuentes** [comment]
Finalmente se utilizó entrust para crear los roles y permisos. Queda pendiente definir bien los permisos de los 4 roles que va a tener el sistema.
