### ISSUE TITLE
Diferente tabla de asistidos si la request viene de un celular

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#51]
sacar los campos no tan necesarios si el usuario logueado está navegando desde un celular.
hay que ver que campos sacamos de la view y cuáles dejamos.

se podría usar esto.
https://github.com/jenssegers/laravel-agent

**Comment by aguspuentes** [comment]
Se definen tablas genéricas list_people, list_interactions y list_users que validan el dispositivo del cual proviene la request y se utilizan en todas las views que precisan cargar alguna tabla.
