### ISSUE TITLE
el primer usuario registrado deberia ser admin (instalador)

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#63]
cuando un usuario se registra, y no hay ninguno registrado, ese se deberìa poner automáticamente como admin. (se debería crear el rol y los permisos)

**Comment by aguspuentes** [comment]
El primer usuario se crea automáticamente en la seed luego de crear los roles y permisos. La idea es entregar el sistema con un usuario master que tenga acceso completo e irrestricto. Para eso se creó el usuario con nombre "Administrador" cuyo mail es el mismo que se utiliza para enviar las alertas al agregar interacciones.

**Comment by CrimsonGlory** [comment]
La seed es algo que se usa para development. Para que te llene la base de datos con cosas.
No es un instalador.

**Comment by Goolsc** [comment]
Vi que me lo asignaste javi.
Lo agrego como primer usuario del databaseseeder o queres que directamente
no haya un seed? La idea seria que el Administrador este hardcodeado ya en
el programa. Que como dice agus, se entregue ya con un "Administrador"

2015-05-22 9:51 GMT-03:00 CrimsonGlory notifications@github.com:

**Comment by CrimsonGlory** [comment]
La seed es para otra cosa. Olvidense.
Hay que hacer que cuando entren a la plataforma y no hay ningun usuario te redireccione a /setup donde te creas un usuario, y te da para configurar otras cosas como una lista inicial de tags.
Una vez hecho el setup, si alguien intenta entrar a /setup que le de 404.
Fijate de bajarte wordpress para ver como es ahí el setup inicial.
