### ISSUE TITLE
Subir otros tipos de archivos

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#68]
Se deberían poder subir otro tipo de archivos que no sean imágenes. 
Salvo .php\* y .htaccess creo que es seguro (desde el punto de vista del servidor) subir cualquier cosa.
Igual esto no es solo agregar una lista de extensiones (que la tenemos que armar). 
Hay que modificar
[ ] - para que el avatar solo se cambie si lo que subió es una imágen.
[ ] - que en la galería de de fotos (person/{id}/photos) solo tome las fotos, salteando los otros archivos.
[ ] - en el perfil del asistido, una lista de los archivos subidos (que no sean imágenes), con un link a cada uno.

**Comment by aguspuentes** [comment]
Estoy de acuerdo en que se puedan subir otros tipos de archivos, por ejemplo si un profesional quisiera subir un PDF con información sobre un asistido que atendió. No obstante, dejaría esta issue para más adelante para consultar con la gente de Posaderos para ver si es común que quieran subir algún otro tipo de archivo y quien podría ver esos archivos. Dependiendo de su respuesta se verá si conviene hacer una nueva view para ver por ejemplo archivos clínicos de un paciente o si se agregarán links desde la misma página del asistido para ver esa información.
