### ISSUE TITLE
el usuario puede agregar a "favoritos" a un asistido.

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#70]
[ ] crear una nueva tabla favorites
[ ] Que en perfil del asistido figura una estrellita, pero 'vacia'. y al agregar a favoritos (con un click), la estrellita se pone llena.
[ ] en el menu dropdown de arriba a la derecha debería estar "favoritos".

Hay que ver si se debería poner para que puedan poner como favorito una interacción o un usuario, o lo dejamos solo para asistido.

**Comment by aguspuentes** [comment]
Acá hay un link de Github que muestra una forma de agregar "like" o "favorite":

https://github.com/rtconner/laravel-likeable
