### ISSUE TITLE
edad en la view

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#79]
Ya que a veces tenemos la fecha de nacimiento, podríamos poner la edad en la view. Quizás en el título.
Ejemplo "Pepe gomez, 56 años"
qué les parece?

**Comment by aguspuentes** [comment]
No se si vale la pena poner la edad en el título de la view, tal vez les puede ser más útil ver la edad en la tabla de asistidos para no tener que ir a cada asistido para ver la edad.
De todas formas es un tema visual, de última les preguntamos a la gente de Posaderos.
