### ISSUE TITLE
Búsqueda avanzada: Al buscar asistidos en mayúsculas se traen todos los asistidos

### ISSUE THREAD

**Issue by aguspuentes** [CrimsonGlory/posaderos#81]
Si en la página de búsqueda de asistidos todos los caracteres ingresados están en mayúscula se traen todos los asistidos existentes.

**Comment by CrimsonGlory** [comment]
ahhhh. alto bug.

**Comment by aguspuentes** [comment]
Si en la página de búsqueda escribís por ejemplo "AAAA" y le das buscar te muestra todos los asistidos, no se por qué.

**Comment by CrimsonGlory** [comment]
rarisimo. Una solución fácil es convertirlo a minúscula apenas entra al método del controller. Es llamar a strtolower(). Pero igual me gustaría saber por qué pasa esto.

**Comment by aguspuentes** [comment]
Es exactamente lo que estoy haciendo. Estoy probando por las dudas todos los casos.
