### ISSUE TITLE
CSRF en addFavorite y removeFavorite

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#86]
el CSRF sigue funcionando. habría que pasarlo de GET a POST como todos los forms, ahí el csrf_token se pone solo.

**Comment by aguspuentes** [comment]
El POST no me está funcionando y no se por qué, por eso lo dejé con GET. Fijate si vos lográs que funcione, capaz estoy poniendo algo mal y no me estoy dando cuenta cual es el problema.
