### ISSUE TITLE
Agregar tipo de exportación CSV a los listados.

### ISSUE THREAD

**Issue by aguspuentes** [CrimsonGlory/posaderos#90]
A pedido de la gente de Posaderos, hay que agregar un combo en los listados que contenga los tipos de exportación:
- PDF
- CSV

**Comment by CrimsonGlory** [comment]
Para el CVS hay que poner todas las strings entre comillas, y escapear el contenido. (comillas, y backslashes). Sino alguien pone un nombre con , o " o \ y el CSV ya no sirve.
También se puede usar algo como esto
http://packalyst.com/packages/package/maatwebsite/excel
