### ISSUE TITLE
Hacer el instalador (docker)

### ISSUE THREAD

**Issue by aguspuentes** [CrimsonGlory/posaderos#92]
Habría que estudiar como hacer un instalador para entregar la primera versión del sistema (específicamente hay que estudiar como funciona docker con los contenedores y como los linkea). Además de la instalación y la creación de las tablas se deberían llenar las tablas de roles y permisos y se debería crear un usuario administrador por defecto con todos los permisos para que se pueda comenzar a operar.

**Comment by CrimsonGlory** [comment]
en parte es lo que dije en #63

**Comment by aguspuentes** [comment]
Es cierto, pero me parece que al hacer el instalador se deberían tener en cuenta esas cosas para dejarles el sistema con el usuario y roles por default, por eso lo repetí en esta issue. Podría haberlo referenciado a la issue #63 también.

**Comment by CrimsonGlory** [comment]
Logré hacer funcionar el Docker. Me falta generar la imagen y subirla.

**Comment by CrimsonGlory** [comment]
La parte de docker ya está, así que cierro esto. El resto que falta hacer ya está en #63
