### ISSUE TITLE
se debería guardar el uploader del archivo.

### ISSUE THREAD

**Issue by CrimsonGlory** [CrimsonGlory/posaderos#95]
En este momento no estamos guardando quién sube el archivo. Es un cambio fácil de hacer que puede servir.
hay que hacer
[ ] una migration con una nueva columna en fileentries llamada uploader_id;
[ ] que uploader_id sea una foreign key
[ ] la relationship. user has_many fileentries. (y por otro lado el belongs)
[ ] agregar una línea en el fileentrycontroller para que se guarde el id.

**Comment by aguspuentes** [comment]
Me parece una buena idea guardar el id del usuario que subió la foto. Tal vez en el futuro se quiera ver qué usuario subió tal foto o todas las fotos subidas por algún usuario.
